yiming1234:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: nottinghamwall
    username: pleasure1234
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tN1XwzBPpGZY6MhB3Sj
    access-key-secret: SYm17YAhe8L3iOl175sa7lKRF9IUD7
    bucket-name: yiming1234
  redis:
    host: localhost
    port: 6379
    password: root
  wechat:
    appid:  wxc57c61bf271c2e18
    secret: 34ccd4b2b9c10d9da301c983d7a4d822