# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: NottinghamWall-backend 自动化打包发放
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
 build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn package -B -DskipTests --file backend/wall-server/pom.xml

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          backend/wall-server/target/wall-server-*.jar
        tag_name: NottinghamWall-backend v1.0
