name: Node.js Package Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'admin/package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: ./admin

  check-version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Check package.json version
        id: check_version
        run: |
          # Fetch the previous commit
          git fetch --depth=2
          # Extract the current and previous version
          CURRENT_VERSION=$(jq -r .version < ./admin/package.json)
          PREV_VERSION=$(git show HEAD~1:./admin/package.json | jq -r .version)
          echo "Current version: $CURRENT_VERSION"
          echo "Previous version: $PREV_VERSION"
          
          if [ "$CURRENT_VERSION" != "$PREV_VERSION" ]; then
            echo "Version has changed"
            echo "version_changed=true" >> $GITHUB_ENV
          else
            echo "Version has not changed"
            echo "version_changed=false" >> $GITHUB_ENV
          fi

  publish:
    runs-on: ubuntu-latest
    needs: check-version
    if: env.version_changed == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - name: Configure npm for npm registry
        run: |
            echo "@pleasure1234:registry=https://registry.npmjs.org/" > .npmrc
            echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
        working-directory: ./admin
         
      - name: Publish to npm
        run: npm publish
        working-directory: ./admin
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Configure npm for GitHub Packages
        run: |
          echo "@Pleasurecruise:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> .npmrc
        working-directory: ./admin
         
      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/
        working-directory: ./admin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
